WebBooks/WebBooks/urls.py
from django.contrib import admin
from catalog import views
from registration import views as reg_views
from django.urls import include, re_path, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('sign_up/', reg_views.sign_up, name="sign_up"),
    path('about_us/', views.about_us, name="about_us"),
    path('authors_add/', views.authors_add, name="authors_add"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('edit1/<int:id>/', views.edit1, name="edit1"),
    path('create/', views.create, name="create"),
    path('delete/<int:id>/', views.delete, name="delete"),
    path(r'cart/', views.cart, name='cart'),
    re_path('^book/create/$', views.BookCreate.as_view(), name="book_create"),
    re_path(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    re_path(r'^books/$', views.book_list, name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^book/update/(?P<pk>\d+)$', views.BookUpdate.as_view(), name="book_update"),
    re_path(r'^book/delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name="book_delete"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre", verbose_name="Book genre")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']


class Language(models.Model):
    name = models.CharField(max_length=20, help_text="Enter a book language", verbose_name="Book language")

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100, help_text="Enter author first name", verbose_name="Author first name")
    last_name = models.CharField(max_length=100, help_text="Enter author last name", verbose_name="Author last name")
    date_of_birth = models.DateField(help_text="Enter a author`s date of birth",
                                     verbose_name="Author date of birth",
                                     null=True,
                                     blank=True)
    date_of_death = models.DateField(help_text="Enter a author`s date of death",
                                     verbose_name="Author date of death",
                                     null=True,
                                     blank=True)

    def __str__(self):
        return self.last_name

    class Meta:
        ordering = ['-id']


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text="Enter a book name",
                             verbose_name="Book name")
    price = models.FloatField(help_text="Enter price of this book",
                              verbose_name='Book price',
                              default=0)
    genre = models.ForeignKey('Genre',
                              on_delete=models.CASCADE,
                              help_text="Enter a book genre",
                              verbose_name="Book genre", null=True)
    language = models.ForeignKey('Language',
                                 on_delete=models.CASCADE,
                                 help_text="Enter a book language",
                                 verbose_name="Book language", null=True)
    author = models.ManyToManyField('Author',
                                    help_text="Enter author",
                                    verbose_name="Book author")
    summary = models.TextField(max_length=1000,
                               help_text="Enter description of this book",
                               verbose_name='Book summary')
    isbn = models.CharField(max_length=13,
                            help_text="Must be 13 symbols in length")

    image = models.ImageField(null=True, blank=True, upload_to="images/")

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])
    display_author.short_description = 'Authors'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def get_image(self):
        return f'/media/{self.image}/'

    class Meta:
        ordering = ['-id']


class Cart(models.Model):
    user = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                )
    books = models.ForeignKey(Book,
                              on_delete=models.CASCADE,)
    quantity = models.IntegerField('quantity',
                                   blank=False,
                                   default=1,
                                   help_text='Quantity books in order')


class Status(models.Model):
    name = models.CharField(max_length=20, help_text="Enter a book status", verbose_name="Book status")

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    ivn_nom = models.CharField(max_length=20,
                               null=True,
                               help_text="Enter the inventory number of the book",
                               verbose_name="Inventory number")
    imprint = models.CharField(max_length=200,
                               null=True,
                               help_text="Enter publisher and year of release",
                               verbose_name="Publisher")
    status = models.ForeignKey('Status',
                               on_delete=models.CASCADE,
                               null=True,
                               help_text='Edit a book status',
                               verbose_name="Book status")
    due_back = models.DateField(null=True,
                                blank=True,
                                help_text="Enter status expiration date",
                                verbose_name="Expiration date")
    borrower = models.ForeignKey(User,
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True,
                                 verbose_name="Customer",
                                 help_text="Select book customer")

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return f"{self.ivn_nom} {self.book} {self.status}"

WebBooks/catalog/forms.py
from django import forms
from django.forms import ModelForm
from datetime import date
from .models import Book
from django.core.exceptions import ValidationError


class AuthorsForm(forms.Form):
    first_name = forms.CharField(label="Author first name")
    last_name = forms.CharField(label="Author last_name name")
    date_of_birth = forms.DateField(label="Birth date",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_death = forms.DateField(label="Death date",
                                    initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))


class BookModelForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'genre', 'language', 'author', 'summary', 'isbn']

WebBooks/catalog/views.py
import random

from django.shortcuts import render
from django.http import *
from .forms import AuthorsForm
from django.views import generic
from .models import Book, Author, BookInstance, Genre, Cart
from django.core.paginator import Paginator
from django.core.exceptions import ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book


def index(request):
    books = []
    all_books = Book.objects.all()
    while len(books) < 12:
        book = random.choice(all_books)
        if book not in books:
            books.append(book)
    # print(books)
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact=2).count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    return render(request, 'index.html', context={'num_books': num_books,
                                                  'num_instances': num_instances,
                                                  'num_instances_available': num_instances_available,
                                                  'num_authors': num_authors,
                                                  'num_visits': num_visits,
                                                  'books': books[:4],
                                                  'books2': books[4:8],
                                                  'books3': books[8:]})


def cart(request):
    if request.method == "POST":
        if request.POST.get('delete'):
            book = Cart.objects.get(id=request.POST.get('delete'))
            book.delete()
        elif request.POST.get('increment'):
            book = Cart.objects.get(id=request.POST.get('increment'))
            book.quantity = book.quantity + 1
            book.save()
        elif request.POST.get('decrement'):
            book = Cart.objects.get(id=request.POST.get('decrement'))
            if book.quantity > 1:
                book.quantity = book.quantity - 1
                book.save()
        elif request.POST.get('quantity'):
            # print(request.POST)
            book = Cart.objects.get(id=request.POST.get('book_id'))
            if int(request.POST.get('book_id')) > 0:
                book.quantity = int(request.POST.get('quantity'))
                book.save()
    cart = Cart.objects.filter(user__exact=request.user.id)
    return render(request, 'catalog/cart.html', context={'cart': cart})


def create(request):
    if request.method == "POST":
        author = Author()
        author.first_name = request.POST.get("first_name")
        author.last_name = request.POST.get("last_name")
        author.date_of_birth = request.POST.get("date_of_birth")
        author.date_of_death = request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/authors_add/")


def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect("/authors_add/")
    except Author.DoesNotExist:
        return HttpResponseNotFound("<h2>Author not found</h2>")


def edit1(request, id):
    author = Author.objects.get(id=id)

    if request.method == "POST":
        author.first_name = request.POST.get("first_name")
        author.last_name = request.POST.get("last_name")
        author.date_of_birth = request.POST.get("date_of_birth")
        author.date_of_death = request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/authors_add/")
    else:
        # print(author.date_of_birth)
        return render(request, "edit1.html", {"author": author})


def authors_add(request):
    author = Author.objects.all()
    authorsform = AuthorsForm()
    return render(request, 'catalog/author_add.html', {"form": authorsform, "author": author})


def book_list(request):
    # print('GET: ',request.GET)
    # print('POST: ', request.POST)
    # print(request.get_full_path())
    # print(dir(request))
    books = Book.objects.all()
    filters = []
    if request.method == 'GET':
        genres_filter = request.GET.getlist('genres')
        authors_filter = request.GET.getlist('authors')
        filters += genres_filter + authors_filter
        genre_id_list = []
        authors_id_list = []
        # books = Book.objects
        if genres_filter:
            for genre in genres_filter:
                try:
                    genre_id_list.append(Genre.objects.get(name=genre))
                except Genre.DoesNotExist:
                    pass
            books = Book.objects.filter(genre__in=genre_id_list)
        if authors_filter:
            for author in authors_filter:
                try:
                    authors_id_list.append(Author.objects.get(first_name=author))
                except Genre.DoesNotExist:
                    pass
                books = books.filter(author__in=authors_id_list)
    genres = Genre.objects.all()
    authors = Author.objects.all()
    paginator = Paginator(books, 9)  # Show 9 books per page.
    is_paginated = True if paginator.num_pages > 1 else False
    page_number = request.GET.get('page')
    # print('page_number',page_number)
    page_obj = paginator.get_page(page_number)
    page_range = list(paginator.page_range)
    # print(page_range)
    return render(request, 'catalog/book_list.html', {'book_list': books,
                                                      'genres': genres,
                                                      'authors': authors,
                                                      'page_obj': page_obj,
                                                      'page_range': page_range,
                                                      'is_paginated': is_paginated,
                                                      'filters': filters
                                                      })


def about_us(request):
    return render(request, 'about_us.html')


class BookListView(generic.ListView):
    model = Book
    paginate_by = 9


class BookDetailView(generic.DetailView):
    model = Book

    # template_name = 'book_detail.html'

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        # print(request.POST)
        if request.POST.get('add_to_cart'):
            cart = Cart()
            cart.books = Book.objects.get(id=request.POST.get('add_to_cart'))
            cart.user = User.objects.get(id=request.POST.get('user'))
            cart.save()
        self.object = self.get_object()
        context = super(BookDetailView, self).get_context_data(**kwargs)
        return self.render_to_response(context=context)


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Универсальный класс представления списка книг,
    находящихся в заказе у текущего пользователя. """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='1').order_by('due_back')


class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

WebBooks/catalog/templates/catalog/author_add.html
{% extends 'base_generic.html' %}
{% block content %}
    {% if user.is_staff %}
        <h3>Authors list in DB</h3>
            <table>
                <thead><th>Id</th><th>----First name----</th><th>Last name</th></thead>

            {% if author %}
                {% for author in author.all%}
                    <tr>
                        <td>{{author.id}}</td>
                        <td>{{author.first_name}}</td>
                        <td>{{author.last_name}}</td>
                        <td><a href="/edit1/{{author.id}}">Change</a> ,
                            <a href="/delete/{{author.id}}">Remove</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <p>DB has not any authors</p>
            {% endif %}
            </table>
            <h3>Add authors to DB</h3>
            <form method="post" action="/create/">
                {% csrf_token %}
                <table>
                    {{ form }}
                </table>
                <input type="submit", value="Save">
            </form>
    {% else %}
        <h1>Please login in stuff account to see this page</h1>
    {% endif %}
{% endblock content %}

WebBooks/catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Authors list in DB</h1>
    {% if author_list %}
        {% for author in author_list %}
        <p>{{author.first_name}} {{author.last_name}},
            <strong>Born:</strong>{{author.date_of_birth}},
            <strong>Death:</strong>{{author.date_of_death}}</p>
        {% endfor %}
    {% else %}
        <p>No authors in DB</p>
    {% endif %}

{% endblock content %}

WebBooks/catalog/templates/catalog/book_confirm_delete.html
{% extends 'base_generic.html' %}s
{% block content %}

    <h1>Delete book</h1>
    <p>Are you sure you want to delete the book: {{ book }}?</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete" />
    </form>
{% endblock content %}

WebBooks/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <img src="{{ book.get_image }}" alt="" height=320 width=212>
            </div>

            <div class="col-md-8">
                <h1>Book name: {{ book.title }}</h1>
                <p><strong>Genre: </strong> {{ book.genre }}</p>
                <p><strong>Summary: </strong> {{ book.summary }}</p>
                <div class="row">
                    <div class="col-md-6">
                        <p><strong>ISBN: </strong> {{ book.isbn }}</p>
                        <p><strong>Language: </strong> {{ book.language }}</p>
                        {% for author in book.author.all %}
                            <p><strong>Author: </strong>
                                <a href="">{{ author.first_name }}
                                        {{ author.last_name }}</a></p>
                        {% endfor %}
                    </div>
                    <div class="col-md-6">
                        <p><strong>{{ book.price }}$</strong></p>
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="add_to_cart" value="{{ book.id }}">
                            <input type="hidden" name="user" value="{{ user.id }}">
                            <input type="Submit" class="btn btn-outline-success"  value="Add to cart">
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
        <div class="row">
            <div style="margin-left:20px;margin-top:20px;">
                <h4>Number of books in DB</h4>
                {% for copy in book.bookinstance_set.all %}
                    <hr><p class="{% if copy.status == 1 %} text-success
                                {% elif copy.status == 2 %} text-danger
                                {% else %} text-warning
                                {% endif %}"> {{ copy.get_status_display }}</p>
                    <p><strong>Imprint: </strong> {{ book.imprint }}</p>
                    <p class="text-muted"><strong>ID: </strong> {{ book.id }}</p>
                    <p><strong>Status: </strong> {{ book.status }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
<p><strong>Author: </strong> <a href="">{{ author.first_name }} {{ author.last_name }}</a></p>

WebBooks/catalog/templates/catalog/book_form.html
{% extends 'base_generic.html' %}
{% block content %}
    {% if user.is_staff %}
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit", text="Save">
        </form>
    {% endif %}
{% endblock content %}

WebBooks/catalog/templates/catalog/book_list.html
{% extends "base_catalog.html" %}

{% block content %}
<div class="container bootstrap snipets"> 
    <h1 class="text-center text-muted">List of books</h1>
    {% if book_list %}
    <ul class="gap-3">
        <div class="row gy-3 flow-offset-1 ">
            {% for book in page_obj %}
            
             <div class="col-xs-6 col-md-4">
                    <div class="card h-100" style="width: 14rem;">
                        <a href="{{ book.get_absolute_url }}">
                            <img  class="card-img-top" src="{{ book.get_image }}" alt="" height=320 width=212>
                        </a>
                        <div class="card-body">
                            <div class="caption">
                            <h6>{{ book.title }}</h6><span class="price">
                                <span class="price">Price</span>
                                <span class="price sale">${{ book.price }}</span>
                            </div>
                        </div>
                    </div>
            </div>  
            {% endfor %}
        
        </div>
    </ul>
    {% else %}
    <p>Databaase has no books</p>
    {% endif %}
 </div> 
{% endblock %}

WebBooks/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% block content %}
    <h1>Books in order</h1>
    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}
                                text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">
                        {{ bookinst.book.title }}
                    </a>
                    ({{ bookinst.due_back }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books in order</p>
    {% endif %}
{% endblock content %}

WebBooks/catalog/templates/catalog/cart.html
{% extends 'base_generic.html' %}
{% load static %}
{% load django_template_maths %}
{% block head %}
<style>
  /* Chrome, Safari, Edge, Opera */
  input::-webkit-outer-spin-button,
  input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }
  
  /* Firefox */
  input[type=number] {
    -moz-appearance: textfield;
  }
  </style>
  <script>
    function sendQuantity() {
      document.getElementById("quantity_form").submit();
    }
  window.onload = function(){
    var sum = 0;
    var quantity = [
          {% for book in cart %}
            {{ book.quantity }},
          {% endfor %}
        ];
    var price = [
          {% for book in cart %}
            {{ book.books.price }},
          {% endfor %}
    ];
    for (let i=0;i<price.length;i++){
      sum += quantity[i]*price[i];
    };
    document.getElementById("value1").innerHTML = '$'+sum.toFixed(2);
  };
    </script>
{% endblock head %}
{% block content %}
{% if cart %}
<section class="h-100" style="background-color: #eee;">
    <div class="container h-100 py-5">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-10">
  
          <div class="d-flex justify-content-between align-items-center mb-4">
            <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
            {% comment %} <div>
              <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!" class="text-body">price <i
                    class="fas fa-angle-down mt-1"></i></a></p>
            </div> {% endcomment %}
          </div>
          {% for book in cart %}
            <div class="card rounded-3 mb-4">
                <div class="card-body p-4">
                <div class="row d-flex justify-content-between align-items-center">
                    <div class="col-md-2 col-lg-2 col-xl-2">
                    <img src="{{book.books.get_image }}"
                        class="img-fluid rounded-3" alt="Cotton T-shirt">
                    </div>
                    <div class="col-md-4 col-lg-4 col-xl-4">
                    <p class="lead fw-normal mb-2">{{book.books }}</p>
                    {% comment %} <p><span class="text-muted">Size: </span>M <span class="text-muted">Color: </span>Grey</p> {% endcomment %}
                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 d-flex">
                      <form class="row g-3" method="post" action="" name="quantity_form" id="quantity_form">
                        {% csrf_token %}
                        <input type="hidden" name="book_id" value="{{book.id}}">
                        <div class="col-md-4">
                          <button type="SubmitBtn" class="btn btn-link px-2" name="decrement" value="{{book.id}}"><img src="{% static 'bootstrap-icons-1.8.1/dash-lg.svg' %}" alt="SomeAlternateText"></button>
                        </div>
                        <div class="col-md-4">
                          <input id="form1" min="1" name="quantity" value="{{ book.quantity }}" type="number"
                          class="form-control form-control-sm" onchange="sendQuantity()"/>
                        </div>
                        <div class="col-md-4">
                          <button type="SubmitBtn" class="btn btn-link px-2" name="increment" value="{{book.id}}"><img src="{% static 'bootstrap-icons-1.8.1/plus-lg.svg' %}" alt="SomeAlternateText"></button>
                        </div>
                      </form>
                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 offset-lg-1">
                      {% comment %} book.books.price {% endcomment %}
                    <h5 class="mb-0">${{ book.books.price|mul:book.quantity|add_decimal:2  }}</h5>
                    </div>
                    <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                        <form method="post" action="">
                            {% csrf_token %}
                            <input type="hidden" name = "delete" value="{{book.id}}">
                            <input type="image"  src="{% static 'bootstrap-icons-1.8.1/trash.svg' %}" width="24" height="24">
                        </form>
                    </div>
                </div>
                </div>
            </div>
          {% endfor %}
          <div class="card">
            <div class="card-body">
              <div class="row d-flex justify-content-between align-items-center">
                <div class="col-md-6">
                 
                </div>
                <div class="col-md-2">
                  <h5 class="mb-0" id="value1">$</h5>
                </div>
                <div class="col-md-4">
                  <button type="button" class="btn btn-warning btn-block btn-lg">Proceed to Pay</button>
                </div>
              </div>
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </section>
{% elif user.is_authenticated %}
<div class="container-fluid mt-100">
  <div class="row">
      <div class="col-md-12">
          <div class="card">
              <div class="card-header">
                  <h5>Cart</h5>
              </div>
              <div class="card-body cart">
                  <div class="col-sm-12 empty-cart-cls text-center"> <img src="https://i.imgur.com/dCdflKN.png" width="130" height="130" class="img-fluid mb-4 mr-3">
                      <h3><strong>Your Cart is Empty</strong></h3>
                      <h4>Add something to make me happy :)</h4> <a href="{% url 'books' %}" class="btn btn-primary cart-btn-transform m-3" data-abc="true">continue shopping</a>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
{% else %}
  <div class="container-fluid mt-100">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Cart</h5>
                </div>
                <div class="card-body cart">
                    <div class="col-sm-12 empty-cart-cls text-center"> <img src="https://i.imgur.com/dCdflKN.png" width="130" height="130" class="img-fluid mb-4 mr-3">
                        <h3><strong>Please login </strong></h3>
                        <a href="{% url 'login' %}" class="btn btn-primary cart-btn-transform m-3" data-abc="true">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endif %}
{% endblock content %}